# ALPHA-generated policy patch for AlphaDemoRole
# Apply this to your CloudFormation template

AlphaDemoRole:
  Type: AWS::IAM::Role
  Properties:
    Policies:
      - PolicyName: ALPHALeastPrivilege
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAccess-analyzerUsedActions
              Effect: Allow
              Action:
                - access-analyzer:ListAnalyzers
              Resource: *
              Condition:
                {}
            -
              Sid: AllowApigatewayUsedActions
              Effect: Allow
              Action:
                - apigateway:GetApis
                - apigateway:GetRestApis
              Resource: *
              Condition:
                {}
            -
              Sid: AllowBedrockUsedActions
              Effect: Allow
              Action:
                - bedrock:ListFoundationModels
              Resource: *
              Condition:
                {}
            -
              Sid: AllowCloudformationUsedActions
              Effect: Allow
              Action:
                - cloudformation:DescribeStacks
                - cloudformation:ListStacks
              Resource: *
              Condition:
                {}
            -
              Sid: AllowCloudtrailUsedActions
              Effect: Allow
              Action:
                - cloudtrail:DescribeTrails
                - cloudtrail:GetTrailStatus
                - cloudtrail:ListTrails
              Resource: *
              Condition:
                {}
            -
              Sid: AllowDynamodbUsedActions
              Effect: Allow
              Action:
                - dynamodb:ListTables
              Resource: *
              Condition:
                {}
            -
              Sid: AllowEc2UsedActions
              Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeKeyPairs
                - ec2:DescribeSecurityGroups
                - ec2:DescribeSnapshots
                - ec2:DescribeSubnets
                - ec2:DescribeVolumes
                - ec2:DescribeVpcs
              Resource: *
              Condition:
                {}
            -
              Sid: AllowEcsUsedActions
              Effect: Allow
              Action:
                - ecs:ListClusters
                - ecs:ListServices
              Resource: *
              Condition:
                {}
            -
              Sid: AllowElasticacheUsedActions
              Effect: Allow
              Action:
                - elasticache:DescribeCacheClusters
              Resource: *
              Condition:
                {}
            -
              Sid: AllowEventsUsedActions
              Effect: Allow
              Action:
                - events:ListEventBuses
                - events:ListRules
              Resource: *
              Condition:
                {}
            -
              Sid: AllowIamUsedActions
              Effect: Allow
              Action:
                - iam:GetRole
                - iam:GetUser
                - iam:ListAttachedRolePolicies
                - iam:ListRolePolicies
                - iam:ListRoles
              Resource: *
              Condition:
                {}
            -
              Sid: AllowKmsUsedActions
              Effect: Allow
              Action:
                - kms:ListAliases
                - kms:ListKeys
              Resource: *
              Condition:
                {}
            -
              Sid: AllowLambdaUsedActions
              Effect: Allow
              Action:
                - lambda:ListFunctions20150331
                - lambda:ListLayers20181031
              Resource: *
              Condition:
                {}
            -
              Sid: AllowLogsUsedActions
              Effect: Allow
              Action:
                - logs:DescribeLogGroups
              Resource: *
              Condition:
                {}
            -
              Sid: AllowOrganizationsUsedActions
              Effect: Allow
              Action:
                - organizations:DescribeOrganization
              Resource: *
              Condition:
                {}
            -
              Sid: AllowRdsUsedActions
              Effect: Allow
              Action:
                - rds:DescribeDBInstances
              Resource: *
              Condition:
                {}
            -
              Sid: AllowS3UsedActions
              Effect: Allow
              Action:
                - s3:GetBucketLocation
                - s3:GetBucketMetricsConfiguration
                - s3:GetBucketVersioning
                - s3:ListBuckets
              Resource: *
              Condition:
                {}
            -
              Sid: AllowSecretsmanagerUsedActions
              Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: *
              Condition:
                {}
            -
              Sid: AllowSnsUsedActions
              Effect: Allow
              Action:
                - sns:ListSubscriptions
                - sns:ListTopics
              Resource: *
              Condition:
                {}
            -
              Sid: AllowSsmUsedActions
              Effect: Allow
              Action:
                - ssm:DescribeParameters
              Resource: *
              Condition:
                {}
            -
              Sid: AllowStatesUsedActions
              Effect: Allow
              Action:
                - states:ListStateMachines
              Resource: *
              Condition:
                {}
            -
              Sid: AllowStsUsedActions
              Effect: Allow
              Action:
                - sts:AssumeRole
                - sts:GetCallerIdentity
              Resource: *
              Condition:
                {}